version: "3"

services:
  database:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    environment:
      TZ: Asia/Seoul
    networks:
      - backend
    restart: always
    
  spring-boot:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - 8080:8080
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/archive_asia_prj?characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: archive_asia_prj
      SPRING_DATASOURCE_PASSWORD: archive_asia_prj
    networks:
      - backend
      - frontend
    restart: always
    
networks:
  backend:
  frontend: